### ISSUE TITLE
Request updating for Visual c++ 2019

### ISSUE THREAD

**Issue by theidexisted** [microsoft/vs-dockerfiles#14]
Request updating for Visual c++ 2019, please!

**Comment by ajpenner** [comment]
I belive you can replace https://aka.ms/vs/15/release with https://aka.ms/vs/17/release in Dockerfile to achieve this goal

**Comment by forderud** [comment]
I've just submitted #16 to update the repo to Visual Studio 2019. Crossing my fingers and hoping that the PR will be considered for merging.

**Comment by AndreyMlashkin** [comment]
Is this still maintained?
@gparlakov @heaths
