### ISSUE TITLE
Using Static Links for All Resources

### ISSUE THREAD

**Issue by solvingj** [Microsoft/vs-dockerfiles#4]
A critical concept for modern devops and automated builds in general is reproducible builds. Particularly with build recipes, it's important to make sure that all URL's accessed are static.  

There is currently a simple yet significant obstacle to getting reproducible builds with Dockerfiles with VS Build Tools.  It is visible in your Dockerfiles here: 

`ADD https://aka.ms/vs/15/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe`

This URL, while great for publishing an evergreen link for users to get the "latest version", is non-deterministic by design, and thus not a good fit for use in Dockerfiles. 

In contrast, earlier releases get static URL's. 
https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017#installing-the-earlier-release

We need a way to get static URL's for the latest versions of all the MSVC SKU's please.

**Comment by solvingj** [comment]
The Dockerfile is an important artifact in devops. The specificity of it's contents matter.  People share Dockerfiles on Github and internally within teams and companies. They're often version controlled, and often held in separate branches or folders with names based on their contents.  Different people build them independently in different environments at different times, constantly. People change minor things and rebuild from them frequently.  When Microsoft posts Dockerfiles on Github, potentially tens of thousands of developers will copy them and build them over the course of the next year or two.  

For these and other reasons, it's widely preferable for everyone if a Dockerfile produces the "same" resulting docker image each time it is built, regardless of the date it was built.  It's best if they're stored in folders which describe the version number of the major components they feature (in this case, the OS and build tools). Of course, it's fine to keep a Dockerfile which uses a "latest" URL around for those who want to constantly rebuild and re-test something against the latest version. 

Example of how this repository might should look over time as new versions of build tools are released: 
https://github.com/conan-io/conan-docker-tools

At the end of the day, the most important part of this request was that many of us just need a way to get a static URL to the most recently released version of VS Build tools. This seems perfectly reasonable and practical.  Each release is ultimately going to get a static link when it hits the "Previous Releases" page, we'd just like to have that link when it's released so we can create our static Dockerfiles for that version.

**Comment by solvingj** [comment]
It looks like somebody named Stan asked a related question on your blog 9 months ago.  https://blogs.msdn.microsoft.com/heaths/2017/09/18/installing-build-tools-for-visual-studio-2017-in-a-docker-container/

**Comment by heaths** [comment]
I understand that in DevOps reproducibility is important. That's why docker images can be built and pushed to a registry and serve as the fixed environment you should use. This is no different than the plethora of, for example, Linux images that just run `apt-get install` to get the latest of a bunch of different tools and libraries? Once you've built an image and tested your runtime components, pushing that image ensures that every machine that pulls it has the exact same version every time. That's how the stable environment is kept, and is one of the major design goals of docker images. If you're trying to recreate container images with the same contents, a better approach would be to rely on file system layering. Get your dependencies installed first into a tagged image, and build on top of that your more dynamic components.

If that doesn't work, our currently supported approach is to create and - whenever desired - update a network layout: https://docs.microsoft.com/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2017

**Comment by solvingj** [comment]
Indeed, you are right about these things.  Pushing an image and sharing it in an environment is ideal, and a good part of the solution. Also, it's true that historically most sample Dockerfiles do things like `apt install` and use the latest.  However, these are very superficial points about the devops ecosystem around docker.  This does not begin to represent the vast diversity of how people use Docker in OSS and Enterprise.

I can accept that you've closed the ticket as wontfix, but I still want to share an example of what most production-targeting enterprise and OSS Dockerfiles look like when deterministic builds are necessary. Based on your comments, it doesn't seen like you've seen any like this before, but it is the standard for production Dockerfiles that I have worked with, where version numbers for everything are paramount (especially compiler versions).  Hopefully this will help to better inform your future decisions about the VS Build Tools Dockerfiles.  

```
FROM ubuntu:artful

LABEL maintainer="Luis Martinez de Bartolome <luism@jfrog.com>"

ENV LLVM_VERSION=4.0 \
    CC=clang \
    CXX=clang++ \
    CMAKE_C_COMPILER=clang \
    CMAKE_CXX_COMPILER=clang++

RUN dpkg --add-architecture i386 \
    && apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
    python-dev=2.7.14-2ubuntu1 \
       sudo=1.8.20p2-1ubuntu1 \
       wget=1.19.1-3ubuntu1 \
       git=1:2.14.1-1ubuntu4 \
       vim=2:8.0.0197-4ubuntu5 \
       g++-multilib=4:7.2.0-1ubuntu1 \
       clang-${LLVM_VERSION}=1:4.0.1-6 \
       llvm-${LLVM_VERSION}=1:4.0.1-6 \
       llvm-${LLVM_VERSION}-dev=1:4.0.1-6 \
       llvm-${LLVM_VERSION}-runtime=1:4.0.1-6 \
       llvm=1:4.0-37~exp3ubuntu1 \
       make=4.1-9.1 \
       valgrind=1:3.13.0-1ubuntu2 \
       libc6-dev-i386=2.26-0ubuntu2.1 \
       libgmp-dev=2:6.1.2+dfsg-1 \
       libmpfr-dev=3.1.6-1 \
       libmpc-dev=1.0.3-2 \
       nasm=2.13.01-2 \
       dh-autoreconf=14 \
       libffi-dev=3.2.1-6 \
       libssl-dev=1.0.2* \
       ninja-build=1.7.2-3 \
       libc++-dev=3.9.1-3 \
       libc++-dev:i386=3.9.1-3 \
       libc++abi-dev=3.9.1-3 \
       libc++abi-dev:i386=3.9.1-3 \
       pkg-config=0.29.1-0ubuntu2 \
       subversion=1.9.7-2ubuntu1 \
       ca-certificates=20170717 \
    && update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/cc cc /usr/bin/clang-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-${LLVM_VERSION} 100 \
    && update-alternatives --install /usr/bin/cpp cpp /usr/bin/clang++-${LLVM_VERSION} 100 \
    && ln -s /usr/include/locale.h /usr/include/xlocale.h \
    && rm -rf /var/lib/apt/lists/* \
    && wget -q --no-check-certificate https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.tar.gz \
    && tar -xzf cmake-3.12.1-Linux-x86_64.tar.gz \
    && cp -fR cmake-3.12.1-Linux-x86_64/* /usr \
    && rm -rf cmake-3.12.1-Linux-x86_64 \
    && rm cmake-3.12.1-Linux-x86_64.tar.gz 
```

**Comment by heaths** [comment]
Thank you for your insight. We will consider this as we look toward future versions, not only for Build Tools on Docker but compilers in general. We are aware of the feedback about maintaining compiler versions and are considering different approaches.

FWIW, I do not include samples among the Dockerfiles to which I referred, but to files used in production like https://github.com/moby/moby/blob/5d82d77a6df0c95bb5986ace1255de424c700b33/Dockerfile#L27-L49. And you're absolutely right - the base image is of a specific version of go - but the various libraries are not. And this is perhaps a good compromise: as with all software, we make not only reliability fixes but security fixes in our runtime code (e.g. libraries) that we want to make sure people get. While compilers certainly do play a part in security, it's typically not to the extent of runtime code on end users' machines.
