### ISSUE TITLE
Missing something silly..  v15.0 vs v15.9.11

### ISSUE THREAD

**Issue by ByronFaber** [microsoft/vs-dockerfiles#8]
I can create containers with visual studio 2017 in them no problem, but i'm missing something silly.  When I start them up, I see 'v15.0' as the tool version.  On my windows desktop it prints out v15.9.11.

Is there anything specific that generates that, or is implied by it?

**Comment by heaths** [comment]
There are many versions and version patterns used thoughout VS. The role version should always be 15.0, but the version of VS is 15.x. You can't currently specify a ride version you don't have installed, so it doesn't make sense to allow a non-zero minor version number in tools version.

Also, Visual Studio IDE is not supported in a container - only Build Tools is and should meet your needs most often. If building some workload didn't work, please open an issue on https://developer community.visualstudio.com.
