### ISSUE TITLE
Why can't I debug this interactively?

### ISSUE THREAD

**Issue by thejohnfreeman** [microsoft/vs-dockerfiles#9]
I'm a Linux developer trying to set up a Windows container for building cross-platform C++. I have very little experience with Visual Studio, `cmd`, or PowerShell, but enough experience with Docker.

I've tried tailoring the installation command to select exactly the components I want, but it's not working. I can't even run the "built" image to debug; it fails to run, saying `The system cannot find the path specified.` I'm trying to build another image with everything but the installation command, so that I can launch it, run the command manually, and debug it. But not even that works! When I manually execute `vs_buildtools.exe` in a container, it returns immediately without doing anything. What is going on? I've tried a number of different Dockerfiles, but here is one:

```docker
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe
```

```powershell
> docker build . -m 2GB -t sandbox
> docker run --rm -it sandbox
> C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache --installPath VisualStudio --add 'Microsoft.VisualStudio.Workload.VCTools;includeRecommended'
```

I've tried with and without the `--channelUri` options. I've tried with and without `install.cmd` as given in the [advanced instructions](https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container). I've tried with and without the "shell reset". None of it makes a difference.

**Comment by heaths** [comment]
Please continue this thread at https://stackoverflow.com/questions/56917942/why-does-the-visual-studio-build-tools-installer-return-immediately-without-inst/56919365.
